package com.kludwisz.anticracker;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/**
 * This class is used to precalculate a hash of the world seed, then use it as a constant
 * in code segments that are vulnerable to seed cracking.
 */
public class SeedHash {
    private static final Logger LOGGER = LogManager.getLogger();
    private static final boolean ENABLED = true;
    private static final int ITERATIONS = 127;

    private static long result = 0L;

    /**
     * Pre-calculates a hash of the world seed using multiple iterations of a hashing function
     * based on the Xoroshiro128++ PRNG, and stores it in a static field for later access.
     * @param worldSeed The 64-bit seed of the Minecraft world.
     */
    public static void precalculateWorldSeedHash(long worldSeed) {
        if (!ENABLED)
            return;

        long hsh = worldSeed;

        for (int i = 0; i < ITERATIONS; i++) {
            hsh = xrsr128pp(hsh);
        }

        LOGGER.info("[SeedHash] Calculated world seed hash: {}", hsh);
        result = hsh;
    }

    /**
     * Xoroshiro128++ PRNG implementation.
     * @param seed The seed to use by the algorithm.
     * @return The first value generated by a XoroshiroRandomSource when used with the given seed.
     */
    private static long xrsr128pp(long seed) {
        // setSeed(seed)
        final long XL = 0x9e3779b97f4a7c15L;
        final long XH = 0x6a09e667f3bcc909L;
        final long A = 0xbf58476d1ce4e5b9L;
        final long B = 0x94d049bb133111ebL;
        long l = seed ^ XH;
        long h = l + XL;
        l = (l ^ (l >> 30)) * A;
        h = (h ^ (h >> 30)) * A;
        l = (l ^ (l >> 27)) * B;
        h = (h ^ (h >> 27)) * B;
        l = l ^ (l >> 31);
        h = h ^ (h >> 31);

        // nextLong()
        return Long.rotateLeft(l + h, 17) + l;
    }

    /**
     * @return The precalculated hash of the world seed.
     */
    public static long getWorldSeedHash() {
        return result;
    }
}
